from structures.vector import Vector2Dim

# Game Basic Settings
TILE_SIZE = 16
TILE_HEIGHT = TILE_SIZE
TILE_WIDTH = TILE_SIZE

ROWS = 36
COLS = 28
WIDTH = COLS * TILE_SIZE
HEIGHT = ROWS * TILE_SIZE
SCREEN_SIZE = (WIDTH, HEIGHT)

# Movement
UP = Vector2Dim(y=-1)
DOWN = Vector2Dim(y=1)
LEFT = Vector2Dim(x=-1)
RIGHT = Vector2Dim(x=1)
STOP = Vector2Dim()
CHARACTER_SPEED = 100

# Colors
BLACK = (0, 0, 0)
YELLOW = (255, 255, 0)
WHITE = (255, 255, 255)

RED = (255, 0, 0)
PINK = (255, 100, 150)
TEAL = (100, 255, 255)
ORANGE = (230, 190, 40)

# Maze symbols
NODE_SYMBOL = "+"
EMPTY_SPACE_SYMBOL = "0"
VERTICAL_PATH_SYMBOL = "|"
HORIZONTAL_PATH_SYMBOL = "-"
HOUSE_SYMBOL = "H"
GHOST_SPAWN_SYMBOL = "S"

# Pellets symbols
PELLET_SYMBOL = "p"
POWER_PELLET_SYMBOL = "P"

# Ghost settings
CHASE_MODE = "CHASE"
SCATTER_MODE = "SCATTER"
SPAWN_MODE = "SPAWN"
FREIGHT_MODE = "FREIGHT"
GUIDE_MODE = "GUIDE"
GHOST_HOUSE = [[EMPTY_SPACE_SYMBOL, EMPTY_SPACE_SYMBOL, NODE_SYMBOL, EMPTY_SPACE_SYMBOL, EMPTY_SPACE_SYMBOL],
               [EMPTY_SPACE_SYMBOL, EMPTY_SPACE_SYMBOL, VERTICAL_PATH_SYMBOL, EMPTY_SPACE_SYMBOL, EMPTY_SPACE_SYMBOL],
               [NODE_SYMBOL, EMPTY_SPACE_SYMBOL, VERTICAL_PATH_SYMBOL, EMPTY_SPACE_SYMBOL, NODE_SYMBOL],
               [NODE_SYMBOL, HORIZONTAL_PATH_SYMBOL, GHOST_SPAWN_SYMBOL, HORIZONTAL_PATH_SYMBOL, NODE_SYMBOL],
               [NODE_SYMBOL, EMPTY_SPACE_SYMBOL, EMPTY_SPACE_SYMBOL, EMPTY_SPACE_SYMBOL, NODE_SYMBOL]]
